//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFsFinalPeliculas.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_peliculazas
    {
        public int Id { get; set; }
        public string Titulo_de_Pelicula { get; set; }
        public string Director_es_ { get; set; }
        public Nullable<System.DateTime> Fecha_Estreno { get; set; }
        public double Valoracion__10 { get; set; }
        public string Protagonista_s_ { get; set; }
    }
}
